// flow-typed signature: c08b224a01353d8390d340ed52ea86c9
// flow-typed version: <<STUB>>/big-text.js_v^1.0.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'big-text.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'big-text.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'big-text.js/big-text' {
  declare module.exports: any;
}

// Filename aliases
declare module 'big-text.js/big-text.js' {
  declare module.exports: $Exports<'big-text.js/big-text'>;
}
