// flow-typed signature: 684c923b3611b086bfbda4e0708efd75
// flow-typed version: <<STUB>>/flatmap_v^0.0.3/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flatmap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flatmap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flatmap/test/flatmap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flatmap/index' {
  declare module.exports: $Exports<'flatmap'>;
}
declare module 'flatmap/index.js' {
  declare module.exports: $Exports<'flatmap'>;
}
declare module 'flatmap/test/flatmap.js' {
  declare module.exports: $Exports<'flatmap/test/flatmap'>;
}
