// flow-typed signature: 09a6e5e79b61c02fbf57a6b6a6b7daf6
// flow-typed version: <<STUB>>/gwent-api-client_v^3.0.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gwent-api-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gwent-api-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gwent-api-client/dist/createClient' {
  declare module.exports: any;
}

declare module 'gwent-api-client/dist/helpers' {
  declare module.exports: any;
}

declare module 'gwent-api-client/dist/index' {
  declare module.exports: any;
}

declare module 'gwent-api-client/dist/request/index' {
  declare module.exports: any;
}

declare module 'gwent-api-client/dist/request/request' {
  declare module.exports: any;
}

declare module 'gwent-api-client/dist/request/requestList' {
  declare module.exports: any;
}

declare module 'gwent-api-client/dist/request/requestOne' {
  declare module.exports: any;
}

declare module 'gwent-api-client/dist/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gwent-api-client/dist/createClient.js' {
  declare module.exports: $Exports<'gwent-api-client/dist/createClient'>;
}
declare module 'gwent-api-client/dist/helpers.js' {
  declare module.exports: $Exports<'gwent-api-client/dist/helpers'>;
}
declare module 'gwent-api-client/dist/index.js' {
  declare module.exports: $Exports<'gwent-api-client/dist/index'>;
}
declare module 'gwent-api-client/dist/request/index.js' {
  declare module.exports: $Exports<'gwent-api-client/dist/request/index'>;
}
declare module 'gwent-api-client/dist/request/request.js' {
  declare module.exports: $Exports<'gwent-api-client/dist/request/request'>;
}
declare module 'gwent-api-client/dist/request/requestList.js' {
  declare module.exports: $Exports<'gwent-api-client/dist/request/requestList'>;
}
declare module 'gwent-api-client/dist/request/requestOne.js' {
  declare module.exports: $Exports<'gwent-api-client/dist/request/requestOne'>;
}
declare module 'gwent-api-client/dist/types.js' {
  declare module.exports: $Exports<'gwent-api-client/dist/types'>;
}
