// flow-typed signature: 63bdd651b5f0d834a0329d45f4e5b408
// flow-typed version: <<STUB>>/intercalate_v^0.1.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'intercalate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'intercalate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'intercalate/intercalate' {
  declare module.exports: any;
}

declare module 'intercalate/test/intercalate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'intercalate/intercalate.js' {
  declare module.exports: $Exports<'intercalate/intercalate'>;
}
declare module 'intercalate/test/intercalate.js' {
  declare module.exports: $Exports<'intercalate/test/intercalate'>;
}
