// flow-typed signature: 483dd8d27c0c9f23bab6d156a2313b4b
// flow-typed version: <<STUB>>/jsx-dom_v^6.2.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsx-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsx-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsx-dom/lib/index.cjs' {
  declare module.exports: any;
}

declare module 'jsx-dom/lib/index' {
  declare module.exports: any;
}

declare module 'jsx-dom/lib/svg.cjs' {
  declare module.exports: any;
}

declare module 'jsx-dom/lib/svg' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsx-dom/lib/index.cjs.js' {
  declare module.exports: $Exports<'jsx-dom/lib/index.cjs'>;
}
declare module 'jsx-dom/lib/index.js' {
  declare module.exports: $Exports<'jsx-dom/lib/index'>;
}
declare module 'jsx-dom/lib/svg.cjs.js' {
  declare module.exports: $Exports<'jsx-dom/lib/svg.cjs'>;
}
declare module 'jsx-dom/lib/svg.js' {
  declare module.exports: $Exports<'jsx-dom/lib/svg'>;
}
