// flow-typed signature: c26d190a3514924ad616343ee8e99b4f
// flow-typed version: <<STUB>>/remove-accents_v^0.4.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remove-accents'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remove-accents' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remove-accents/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remove-accents/index' {
  declare module.exports: $Exports<'remove-accents'>;
}
declare module 'remove-accents/index.js' {
  declare module.exports: $Exports<'remove-accents'>;
}
declare module 'remove-accents/test.js' {
  declare module.exports: $Exports<'remove-accents/test'>;
}
